import array
from typing import ClassVar, final

from typing_extensions import Buffer

__all__ = [
    "EndSlopes",
    "RationalCubic",
    "RationalCubicSpline",
    "Tension",
    "TensionSpline",
    "VariableDegree",
    "VariableDegreeSpline",
]


@final
class EndSlopes:
    __hash__: ClassVar[None]  # type: ignore[assignment]

    @staticmethod
    def estimated() -> EndSlopes: ...
    @staticmethod
    def clamped(left: float, right: float) -> EndSlopes: ...
    def __eq__(self, value: object, /) -> bool: ...


@final
class RationalCubicSpline:
    def __call__(self, x: float) -> float: ...
    def value(self, x: float) -> float: ...
    def first_derivative(self, x: float) -> float: ...
    def second_derivative(self, x: float) -> float: ...
    def value_batch(self, xs: Buffer) -> array.array[float]: ...
    def first_derivative_batch(self, xs: Buffer) -> array.array[float]: ...
    def second_derivative_batch(self, xs: Buffer) -> array.array[float]: ...
    def value_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    def first_derivative_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    def second_derivative_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    @property
    def domain(self) -> tuple[float, float]: ...
    @property
    def tension_parameters(self) -> list[float]: ...
    @property
    def iterations(self) -> int: ...
    @property
    def is_concave(self) -> bool: ...


@final
class TensionSpline:
    def __call__(self, x: float) -> float: ...
    def value(self, x: float) -> float: ...
    def first_derivative(self, x: float) -> float: ...
    def second_derivative(self, x: float) -> float: ...
    def value_batch(self, xs: Buffer) -> array.array[float]: ...
    def first_derivative_batch(self, xs: Buffer) -> array.array[float]: ...
    def second_derivative_batch(self, xs: Buffer) -> array.array[float]: ...
    def value_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    def first_derivative_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    def second_derivative_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    @property
    def domain(self) -> tuple[float, float]: ...
    @property
    def tensions(self) -> list[float]: ...
    @property
    def iterations(self) -> int: ...


@final
class VariableDegreeSpline:
    def __call__(self, x: float) -> float: ...
    def value(self, x: float) -> float: ...
    def first_derivative(self, x: float) -> float: ...
    def second_derivative(self, x: float) -> float: ...
    def value_batch(self, xs: Buffer) -> array.array[float]: ...
    def first_derivative_batch(self, xs: Buffer) -> array.array[float]: ...
    def second_derivative_batch(self, xs: Buffer) -> array.array[float]: ...
    def value_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    def first_derivative_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    def second_derivative_batch_into(self, xs: Buffer, out: Buffer) -> None: ...
    @property
    def domain(self) -> tuple[float, float]: ...
    @property
    def degrees(self) -> list[float]: ...
    @property
    def is_shape_preserving(self) -> bool: ...


@final
class RationalCubic:
    __hash__: ClassVar[None]  # type: ignore[assignment]

    def __init__(self) -> None: ...
    def fit(self, x: Buffer, y: Buffer) -> RationalCubicSpline: ...
    def with_shape(self, u: float, v: float) -> RationalCubic: ...
    def with_boundary(self, boundary: EndSlopes) -> RationalCubic: ...
    def with_convexity_margin(self, margin: float) -> RationalCubic: ...
    def with_relaxation(self, relaxation: float) -> RationalCubic: ...
    def with_max_iterations(self, max_iterations: int) -> RationalCubic: ...
    @property
    def shape(self) -> tuple[float, float]: ...
    @property
    def boundary(self) -> EndSlopes: ...
    @property
    def convexity_margin(self) -> float: ...
    @property
    def relaxation(self) -> float: ...
    @property
    def max_iterations(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...


@final
class Tension:
    __hash__: ClassVar[None]  # type: ignore[assignment]

    def __init__(self) -> None: ...
    def fit(self, x: Buffer, y: Buffer) -> TensionSpline: ...
    def with_uniform_tension(self, sigma: float) -> Tension: ...
    def with_boundary(self, boundary: EndSlopes) -> Tension: ...
    def with_tolerance(self, tolerance: float) -> Tension: ...
    def with_max_iterations(self, max_iterations: int) -> Tension: ...
    @property
    def uniform_tension(self) -> float | None: ...
    @property
    def boundary(self) -> EndSlopes: ...
    @property
    def tolerance(self) -> float: ...
    @property
    def max_iterations(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...


@final
class VariableDegree:
    __hash__: ClassVar[None]  # type: ignore[assignment]

    def __init__(self) -> None: ...
    def fit(self, x: Buffer, y: Buffer) -> VariableDegreeSpline: ...
    def with_boundary(self, boundary: EndSlopes) -> VariableDegree: ...
    def with_max_degree(self, max_degree: float) -> VariableDegree: ...
    def with_max_iterations(self, max_iterations: int) -> VariableDegree: ...
    @property
    def boundary(self) -> EndSlopes: ...
    @property
    def max_degree(self) -> float: ...
    @property
    def max_iterations(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
